export const dataProdukRekomendasi = [
  {
    id: 1,
    nama: 'Jeruk Mandarin',
    harga: 25000,
    review: 4.5,
    terjual: 130,
    img: '/assets/img/produk-rekomendasi/jeruk-mandarin.png',
    alt: 'jeruk-mandarin.png',
  },
  {
    id: 2,
    nama: 'Melon Madu',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/melon-madu.png',
    alt: 'melon-madu.png',
  },
  {
    id: 3,
    nama: 'Anggur Merah',
    harga: 55000,
    review: 4.5,
    terjual: 170,
    img: '/assets/img/produk-rekomendasi/anggur-merah.png',
    alt: 'anggur-merah.png',
  },
  {
    id: 4,
    nama: 'Brokoli',
    harga: 25000,
    review: 4.5,
    terjual: 130,
    img: '/assets/img/produk-rekomendasi/brokoli.png',
    alt: 'brokoli.png',
  },
  {
    id: 5,
    nama: 'Wortel',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/wortel.png',
    alt: 'wortel.png',
  },
  {
    id: 6,
    nama: 'Sawi Putih',
    harga: 55000,
    review: 4.5,
    terjual: 170,
    img: '/assets/img/produk-rekomendasi/sawi-putih.png',
    alt: 'sawi-putih.png',
  },
  {
    id: 7,
    nama: 'Ayam Broiler Utuh',
    harga: 55000,
    review: 4.5,
    terjual: 170,
    img: '/assets/img/produk-rekomendasi/ayam-broiler-utuh.png',
    alt: 'ayam-broiler-utuh.png',
  },
  {
    id: 8,
    nama: 'Paha Ayam',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/paha-ayam.png',
    alt: 'paha-ayam.png',
  },
  {
    id: 9,
    nama: 'Kulit Ayam',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/kulit-ayam.png',
    alt: 'kulit-ayam.png',
  },
  {
    id: 10,
    nama: 'Ikan Gurame',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/ikan-gurame.png',
    alt: 'ikan-gurame.png',
  },
  {
    id: 11,
    nama: 'Ikan Kerapu',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/ikan-kerapu.png',
    alt: 'ikan-kerapu.png',
  },
  {
    id: 12,
    nama: 'Daging Sapi',
    harga: 40000,
    review: 45.0,
    terjual: 75,
    img: '/assets/img/produk-rekomendasi/daging-sapi.png',
    alt: 'daging-sapi.png',
  },
];